<?php

return [
    [
        'key'  => 'fpc',
        'name' => 'varnish::app.configuration.fpc.title',
        'info' => 'varnish::app.configuration.fpc.info',
        'sort' => 10,
    ], [
        'key'  => 'fpc.configuration',
        'name' => 'varnish::app.configuration.fpc.configuration.title',
        'info' => 'varnish::app.configuration.fpc.configuration.info',
        'icon' => 'settings/store.svg',
        'sort' => 1,
    ], [
        'key'    => 'fpc.configuration.fpc',
        'name'   => 'varnish::app.configuration.fpc.configuration.fpc.title',
        'info'   => 'varnish::app.configuration.fpc.configuration.fpc.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'cache_application',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.title',
                'type'          => 'select',
                'default'       => 'bagisto-built-in',
                'options'       => [
                    ['title' => 'Bagisto Built-in', 'value' => 'bagisto-built-in'],
                    ['title' => 'Varnish (Recommended)', 'value' => 'varnish'],
                ],
                'channel_based' => true,
            ],
            [
                'name'          => 'varnish_access_list',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.access_list.title',
                'info'          => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.access_list.info',
                'type'          => 'text',
                'depends'       => 'cache_application:varnish',
                'default'       => 'localhost',
                'validation'    => 'required_if:cache_application,varnish',
                'channel_based' => true,
            ],
            [
                'name'          => 'varnish_url',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.url.title',
                'info'          => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.url.info',
                'type'          => 'text',
                'depends'       => 'cache_application:varnish',
                'default'       => 'localhost',
                'validation'    => 'required_if:cache_application,varnish',
                'channel_based' => true,
            ],
            [
                'name'          => 'varnish_backend_url',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.backend_url.title',
                'info'          => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.backend_url.info',
                'type'          => 'text',
                'depends'       => 'cache_application:varnish',
                'default'       => '80',
                'validation'    => 'required_if:cache_application,varnish',
                'channel_based' => true,
            ],
            [
                'name'          => 'varnish_backend_port',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.backend_port.title',
                'info'          => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.backend_port.info',
                'type'          => 'text',
                'depends'       => 'cache_application:varnish',
                'default'       => '80',
                'validation'    => 'required_if:cache_application,varnish',
                'channel_based' => true,
            ],
            [
                'name'          => 'varnish_grace_period',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.grace_period.title',
                'info'          => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.grace_period.info',
                'type'          => 'text',
                'depends'       => 'cache_application:varnish',
                'default'       => '300',
                'validation'    => 'required_if:cache_application,varnish',
                'channel_based' => true,
            ],
            [
                'name'          => 'varnish_export_vcl',
                'title'         => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.export_vcl.title',
                'info'          => 'varnish::app.configuration.fpc.configuration.fpc.cache_application.varnish.export_vcl.info',
                'type'          => 'blade',
                'depends'       => 'cache_application:varnish',
                'validation'    => 'required_if:cache_application,varnish',
                'path'          => 'varnish::configuration.export-vcl',
            ],
        ],
    ],
    [
        'key'  => 'fpc.cache_management',
        'name' => 'varnish::app.configuration.fpc.cache_management.title',
        'info' => 'varnish::app.configuration.fpc.cache_management.info',
        'icon' => 'settings/store.svg',
        'sort' => 2,
    ], [
        'key'    => 'fpc.cache_management.purge_cache',
        'name'   => 'varnish::app.configuration.fpc.cache_management.purge_cache.title',
        'info'   => 'varnish::app.configuration.fpc.cache_management.purge_cache.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'purge_cache',
                'title'         => 'varnish::app.configuration.fpc.cache_management.purge_cache.title',
                'type'          => 'blade',
                'path'          => 'varnish::configuration.purge-cache-via-url',
            ],
        ],
    ],
    [
        'key'    => 'fpc.cache_management.purge_full_cache',
        'name'   => '',
        'info'   => '',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'full_purge_cache',
                'title'         => 'varnish::app.configuration.fpc.cache_management.purge_full_cache.title',
                'type'          => 'blade',
                'path'          => 'varnish::configuration.purge-full-cache',
            ],
        ],
    ],
];
